export const rolesEnum = {
  CONTRIBUTOR: 'CONTRIBUTOR',
  STAFF: 'STAFF',
  ADMIN: 'ADMIN',
  TBD: 'TBD',
};

export const onboardingStatusEnum = {
  ONBOARDING_SCHEDULED: 'ONBOARDING_SCHEDULED',
  STALLED: 'STALLED',
  ONBOARDED: 'ONBOARDED',
};

export const pages = {
  ACCOUNT_HOME: 'ACCOUNT_HOME',
  PROFILE: 'PROFILE',
  PITCHES: 'PITCHES',
  RESOURCES: 'RESOURCES',
  USERS: 'USERS'
}
