export const rolesEnum = {
  CONTRIBUTOR: 'CONTRIBUTOR',
  STAFF: 'STAFF',
  ADMIN: 'ADMIN',
  TBD: 'TBD',
};

export const onboardingStatusEnum = {
  ONBOARDING_SCHEDULED: 'ONBOARDING_SCHEDULED',
  STALLED: 'STALLED',
  ONBOARDED: 'ONBOARDED',
  NONE: 'NONE',
};

export const interestsEnum = {
  POLITICS: 'POLITICS',
  EDUCATION: 'EDUCATION',
  HOUSING: 'HOUSING',
  LIT: 'LIT',
  MUSIC: 'MUSIC',
  VISUAL_ARTS: 'VISUAL ARTS',
  STAGE_AND_SCREEN: 'STAGE AND SCREEN',
  FOOD_AND_LAND: 'FOOD AND LAND',
  NATURE: 'NATURE',
  TRANSPORTATION: 'TRANSPORTATION',
  HEALTH: 'HEALTH',
  CANNABIS: 'CANNABIS',
  IMMIGRATION: 'IMMIGRATION',
  FUN: 'FUN',
  NONE: 'NONE',
};

export const racesEnum = {
  AMERICAN_INDIAN_OR_ALASKAN_NATIVE: 'AMERICAN INDIAN OR ALASKAN NATIVE',
  BLACK_OR_AFRICAN_AMERICAN: 'BLACK OR AFRICAN AMERICAN',
  MIDDLE_EASTERN_OR_NORTH_AFRICAN: 'MIDDLE EASTERN OR NORTH AFRICAN',
  NATIVE_HAWAIIAN_OR_PACIFIC_ISLANDER: 'NATIVE HAWAIIAN OR PACIFIC ISLANDER',
  LATINX_OR_HISPANIC: 'LATINX OR HISPANIC',
  WHITE: 'WHITE',
  ASIAN: 'ASIAN',
  OTHER: 'OTHER',
  NONE: 'NONE',
};

export const teamEnum = {
  EDITING: 'EDITING',
  FACT_CHECKING: 'FACT-CHECKING',
  ILLUSTRATION: 'ILLUSTRATION',
  PHOTOGRAPHY: 'PHOTOGRAPHY',
  VISUALS: 'VISUALS',
  WRITING: 'WRITING',
};

export const pages = {
  HOME: 'HOME',
  PROFILE: 'PROFILE',
  PITCHES: 'PITCHES',
  RESOURCES: 'RESOURCES',
  USERS: 'USERS',
};

export const pitchStatusEnum = {
  APPROVED: 'APPROVED',
  PENDING: 'PENDING',
  REJECTED: 'REJECTED',
  NONE: 'NONE',
};

export const assignmentStatusEnum = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  ABANDONED: 'ABANDONED',
  NONE: 'NONE',
};
