export const interestsEnum = {
  POLITICS: 'POLITICS',
  EDUCATION: 'EDUCATION',
  HOUSING: 'HOUSING',
  LIT: 'LIT',
  MUSIC: 'MUSIC',
  VISUAL_ARTS: 'VISUAL ARTS',
  STAGE_AND_SCREEN: 'STAGE AND SCREEN',
  FOOD_AND_LAND: 'FOOD AND LAND',
  NATURE: 'NATURE',
  TRANSPORTATION: 'TRANSPORTATION',
  HEALTH: 'HEALTH',
  CANNABIS: 'CANNABIS',
  IMMIGRATION: 'IMMIGRATION',
  FUN: 'FUN',
  NONE: 'NONE',
};

export const onboardingStatusEnum = {
  ONBOARDING_SCHEDULED: 'ONBOARDING_SCHEDULED',
  STALLED: 'STALLED',
  ONBOARDED: 'ONBOARDED',
  DENIED: 'DENIED',
};

export const racesEnum = {
  AMERICAN_INDIAN_OR_ALASKAN_NATIVE: 'AMERICAN INDIAN OR ALASKAN NATIVE',
  BLACK_OR_AFRICAN_AMERICAN: 'BLACK OR AFRICAN AMERICAN',
  MIDDLE_EASTERN_OR_NORTH_AFRICAN: 'MIDDLE EASTERN OR NORTH AFRICAN',
  NATIVE_HAWAIIAN_OR_PACIFIC_ISLANDER: 'NATIVE HAWAIIAN OR PACIFIC ISLANDER',
  LATINX_OR_HISPANIC: 'LATINX OR HISPANIC',
  WHITE: 'WHITE',
  ASIAN: 'ASIAN',
  OTHER: 'OTHER',
  NONE: 'NONE',
};

export const pitchStatusEnum = {
  APPROVED: 'APPROVED',
  PENDING: 'PENDING',
  DECLINED: 'DECLINED',
  NONE: 'NONE',
};

export const pagesEnum = {
  HOMEPAGE: 'HOMEPAGE',
  PITCHDOC: 'PITCHDOC',
  DIRECTORY: 'DIRECTORY',
  RESOURCES: 'RESOURCES',
};

export const rolesEnum = {
  STAFF: 'STAFF',
  CONTRIBUTOR: 'CONTRIBUTOR',
  ADMIN: 'ADMIN',
};

export const wizardPages = {
  INITIAL_PAGE: 'INITIAL PAGE',
  ONBOARD_1: 'ONBOARD_1',
  ONBOARD_2: 'ONBOARD_2',
  ONBOARD_3: 'ONBOARD_3',
  ONBOARD_4: 'ONBOARD_4',
  ONBOARD_5: 'ONBOARD_5',
  COMPLETION: 'COMPLETION',
};

export const issueTypeEnum = {
  PRINT: 'PRINT',
  ONLINE: 'ONLINE',
};

export const visibilityEnum = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
};

export const statusEnum = {
  ACTIVE: 'Active',
  RECENTLY_ACTIVE: 'Recently Active',
  INACTIVE: 'Inactive',
};

export const issueStatusEnum = {
  MAYBE_IN: 'MAYBE_IN',
  DEFINITELY_IN: 'DEFINITELY_IN',
  IN_EDITS: 'IN_EDITS',
  READY_TO_PUBLISH: 'READY_TO_PUBLISH',
  PUSH: 'PUSH',
};

export const assignmentStatusEnum = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  ABANDONED: 'ABANDONED',
  UNCLAIMED: 'UNCLAIMED',
  NONE: 'NONE',
};

export const editStatusEnum = {
  WRITER_NEEDED: 'Writer Needed',
  FIRST_NEEDED: '1st Needed',
  FIRST_IP: '1st In Progress',
  SECONDS_NEEDED: '2nds Needed',
  SECONDS_IP: '2nds In Progress',
  FC_IP: 'Fact-Checking In Progress',
  THIRDS_NEEDED: '3rds Needed',
  THIRDS_IP: '3rds In Progress',
  READY_TO_PUBLISH: 'Ready to Publish',
  DROPPED: 'Dropped',
  TRANSLATION_IP: 'Translation In Progress',
};
