name: update-stalled-users
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call the update-stalled users API endpoint
        run: |
          curl --request POST \
          --url 'https://hub.southsideweekly.com/api/users/stallUsers' \
          --header 'X-REQUEST-SECRET: ${{ secrets.REQUEST_SECRET }}'